main: io.github.logics4.individualkeepinventory.bukkit.IKI
name: ${project.parent.name}
authors: ["Logics4"]
version: ${project.parent.version}
description: ${project.parent.description}
website: ${project.parent.url}

permissions:
  iki.events.playerdeath.keepinventory:
    default: false
